version: '3'

services:
  api:
    build:
        dockerfile: Dockerfile
        context: .
    depends_on: 
        - db
    environment: 
        DATABASE_URL: db://postgres:pg_password@db:5432/projeto
        NODE_ENV: development
        PORT: 3000
    ports:
        - "8080:3000"
  db:
      image: postgres:10.4
      ports:
        - "5432:5432"
      environment: 
        - POSTGRES_PASSWORD=pg_password
        - POSTGRES_DB=projeto