name: ci-node-workflow
on: 
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Subir banco
        run: docker-compose up -d db 
      - name: Rodar CI
        run: npm ci
      - name: Rodar testes
        run: npm test
      - name: Parar banco
        run: docker-compose down
